# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    openweathermap_api_key: '%env(OPENWEATHERMAP_API_KEY)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    _instanceof:
        App\Exception\Handler\ExceptionHandlerInterface:
            tags: ['app.exception_handler']

    App\Exception\Handler\WeatherExceptionHandler:
        tags:
            - { name: 'app.exception_handler', priority: 20 }

    App\Exception\Handler\HttpExceptionHandler:
        tags:
            - { name: 'app.exception_handler', priority: 10 }

    App\Exception\Handler\DefaultExceptionHandler:
        tags:
            - { name: 'app.exception_handler', priority: -10 }

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
    App\Service\Weather\OpenWeatherMapService:
        arguments:
            $apiKey: '%openweathermap_api_key%'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
